### ISSUE TITLE
Topic '/rosppm/channels' not created?

### ISSUE THREAD

**Issue by Srijal97** [Jaeyoung-Lim/rosppm#8]
I've tried and followed all of the steps given and connected a Turnigy 9X via an Arduino Uno on ROS Kinetic. I am new to ROS so please point out anything that doesn't seem correct. The Arduino has the 'rosppm_arduino' program included in the master branch.

Now firstly, I would like to point out that in the launch/read_Tx.launch file, the baud rate is set to 115200 but it is 57600 in launch/send_Tx.launch file. Is this how its supposed to be? It shows an 'Unable to sync' error for read_Tx.launch at 115200 and connects when I change it 57600.

After launching `roslaunch rosppm send_Tx.launch` and `roslaunch rosppm read_Tx.launch` I do not see `/rosppm/channels` created as mentioned in the instructions. The only topics listed are:

```
srijal@Srijal-PC:~$ rostopic list
/diagnostics
/rosout
/rosout_agg
/rosppm_arduino/read_ppm
/rosppm_arduino/set_ppm
/rosppm_interface/joy_read_channels
/rosppm_interface/joy_set_channels
```
Also I get this error sometimes:

```
[ERROR] [1504288634.686663]: Parameter /rosppm/mode does not exist
```

and on `rostopic echo /rosppm_arduin/read_ppm` I get the following output continously:

```
---
header: 
  seq: 37
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
a: -2.294921875
b: -2.294921875
c: -2.294921875
d: -2.294921875
e: -2.294921875
f: -2.294921875
g: 0.0
h: 0.0
i: 0.0
---
```
And it doesnt change when I move anything on my Transmitter (I have removed the RF module from the back as it is normally done when using simulators). 

What am I doing/What should I try next?
